### ISSUE TITLE
Pubg Mobile KR 1080p

### ISSUE THREAD

**Issue by mustiadam** [MohamedKVIP/MK-PUBG-Mobile-Tool#4]
The 1080P option on the optimizer for PUBG Mobile KR doesn't seem to work 
I have tried it multiple times (with GFX tool) with no success

**Comment by MohamedKVIP** [comment]
The problem will be solved in the update coming in two days.

**Comment by MohamedKVIP** [comment]
Fixed in [v1.0.7](https://github.com/MohamedKVIP/MK-PUBG-Mobile-Tool/releases/tag/v1.0.7)
