### ISSUE TITLE
Tools closed automatically

### ISSUE THREAD

**Issue by go-sudo** [MohamedKVIP/MK-PUBG-Mobile-Tool#7]
Hello, 
the tool close when I click on connect 

python main.py
[#] Starting the GUI app
Traceback (most recent call last):
  File "C:\Users\commu\Downloads\MK-PUBG-Mobile-Tool-main\MK-PUBG-Mobile-Tool-main\src\gfx.py", line 64, in run
    self.app.check_adb_status()
  File "C:\Users\commu\Downloads\MK-PUBG-Mobile-Tool-main\MK-PUBG-Mobile-Tool-main\src\app_functions.py", line 714, in check_adb_status
    raise ValueError("Unknown AdbDisable status.")
ValueError: Unknown AdbDisable status.

Problem Diagnosis

X

System:
CPU:

OpenGL:

Simulator:

VDI:

VDI100:

Rootfs:

Rootfs100:

Microsoft Windows 11 64 Bit
Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
Installed Memory: 48.0 GB
Color Depth: 32 bits 59Hz
Radeon (TM) RX 570 Graphics
4.6.0 Compatibility Profile Context 24.3.1.2 ...
D3D11FeatureLevel: 11.0
APP Market: C:\Program Files\TxGameAssistant\AppMar ...
3.11.3149.80
C:\Program Files\TxGameAssistant\UI
3.21.5141.80
Unknown
Unknown
Unknown
Unknown
Unknown
Unknown
C:\Program Files\TxGameAssistant\AOW_R ..·
3.61.639.101
Shared Directory: E:\Temp\TxGameDownload\MobileGa ...

**Comment by MohamedKVIP** [comment]
To resolve this issue, please follow these steps:

**Run with Administrator Permissions**: Ensure you run the tool with administrator permissions. Right-click on main.py or the shortcut to your Python interpreter and select "Run as administrator".

or Use the [exe Version](https://github.com/MohamedKVIP/MK-PUBG-Mobile-Tool/releases) : If you have an executable (.exe) version of the tool, use that instead. Executable versions often handle permissions and dependencies differently, which can prevent this type of error.
